[package]
name = "wintun"
version = "0.1.0"
edition = "2018"
authors = ["null.black Inc. <opensource@null.black>", "Troy Neubauer <troy@null.black>"]
license = "MIT OR GPLv2"

[dependencies]
widestring = "0.4"
libloading = "0.7"

once_cell = "1.8"
log = "0.4"
rand = "0.8.3"
itertools = "0.10.1"

winapi = { version = "0.3", features = ["synchapi", "winbase", "winerror"] }

[dev-dependencies]
env_logger = "0.8"
winapi = { version = "0.3", features = ["synchapi", "winbase", "winerror", "netioapi", "iptypes", "iphlpapi", "nldef"] }
packet = "0.1.4"
pcap-file = "1.1.1"

